"""
ADIP — Confidence Engine

Calculates explainable, deterministic confidence scores.
Confidence is NEVER generated by the LLM.

Formula:
    Confidence = (
        retrieval_similarity * 0.40 +
        business_rule_match  * 0.25 +
        memory_consistency   * 0.20 +
        signal_strength      * 0.15
    )
"""
from __future__ import annotations

from dataclasses import dataclass

from backend.core.shared_state import ADIPState, AgentResult
from backend.utils.logger import get_logger

logger = get_logger(__name__)


@dataclass
class ConfidenceScore:
    overall: float              # 0.0 – 1.0
    retrieval_similarity: float
    business_rule_match: float
    memory_consistency: float
    signal_strength: float
    breakdown: dict[str, float]

    def as_percentage(self) -> int:
        return round(self.overall * 100)


class ConfidenceEngine:
    """
    Computes deterministic, explainable confidence scores.

    Inputs come from the current ADIPState — retrieval quality,
    business rule activation, memory history, and signal strength.
    """

    WEIGHTS = {
        "retrieval_similarity": 0.40,
        "business_rule_match": 0.25,
        "memory_consistency": 0.20,
        "signal_strength": 0.15,
    }

    def compute(
        self,
        state: ADIPState,
        agent_results: list[AgentResult],
        rule_triggered_count: int = 0,
    ) -> ConfidenceScore:
        """
        Computes the overall confidence score for a set of recommendations.

        Args:
            state: Current ADIPState with retrieval and signal data.
            agent_results: Results from all executed agents.
            rule_triggered_count: Number of business rules that fired.

        Returns:
            ConfidenceScore with breakdown.
        """
        retrieval_similarity = self._compute_retrieval_similarity(state)
        business_rule_match = self._compute_rule_match(rule_triggered_count)
        memory_consistency = self._compute_memory_consistency(state)
        signal_strength = self._compute_signal_strength(state)

        overall = (
            retrieval_similarity * self.WEIGHTS["retrieval_similarity"] +
            business_rule_match * self.WEIGHTS["business_rule_match"] +
            memory_consistency * self.WEIGHTS["memory_consistency"] +
            signal_strength * self.WEIGHTS["signal_strength"]
        )
        overall = min(max(overall, 0.0), 1.0)

        score = ConfidenceScore(
            overall=round(overall, 3),
            retrieval_similarity=round(retrieval_similarity, 3),
            business_rule_match=round(business_rule_match, 3),
            memory_consistency=round(memory_consistency, 3),
            signal_strength=round(signal_strength, 3),
            breakdown={
                "retrieval_similarity": round(retrieval_similarity * self.WEIGHTS["retrieval_similarity"] * 100, 1),
                "business_rule_match": round(business_rule_match * self.WEIGHTS["business_rule_match"] * 100, 1),
                "memory_consistency": round(memory_consistency * self.WEIGHTS["memory_consistency"] * 100, 1),
                "signal_strength": round(signal_strength * self.WEIGHTS["signal_strength"] * 100, 1),
            },
        )

        logger.info(
            f"Confidence computed: {score.as_percentage()}% "
            f"(ret={retrieval_similarity:.2f}, rule={business_rule_match:.2f}, "
            f"mem={memory_consistency:.2f}, sig={signal_strength:.2f})"
        )
        return score

    # ── Component calculators ──────────────────────────────────────────────

    def _compute_retrieval_similarity(self, state: ADIPState) -> float:
        """Average similarity score of retrieved knowledge chunks."""
        if not state.retrieved_chunks:
            return 0.3  # baseline when no retrieval
        scores = [c.similarity_score for c in state.retrieved_chunks]
        return min(sum(scores) / len(scores), 1.0)

    def _compute_rule_match(self, rule_triggered_count: int) -> float:
        """Confidence boost based on how many business rules fired."""
        if rule_triggered_count == 0:
            return 0.4
        elif rule_triggered_count == 1:
            return 0.7
        elif rule_triggered_count == 2:
            return 0.85
        else:
            return 1.0

    def _compute_memory_consistency(self, state: ADIPState) -> float:
        """
        Measures consistency with past memory.
        Higher if past decisions align with current signals.
        """
        if not state.memory_context:
            return 0.5  # neutral — no history
        # Count how many past decisions were approved (positive consistency)
        approved_count = sum(
            1 for m in state.memory_context if m.get("decision") == "approved"
        )
        total = len(state.memory_context)
        return min(0.4 + (approved_count / total) * 0.6, 1.0)

    def _compute_signal_strength(self, state: ADIPState) -> float:
        """Confidence based on number and severity of detected signals."""
        signal_count = len(state.detected_signals)
        if signal_count == 0:
            return 0.2
        elif signal_count == 1:
            return 0.5
        elif signal_count == 2:
            return 0.7
        elif signal_count == 3:
            return 0.85
        else:
            return 1.0
